### ISSUE TITLE
Shop items can't unequipped

### ISSUE THREAD

**Issue by hikasap** [cahidenes/CodeRacer#5]
Shop items can't unequipped

**Comment by cahidenes** [comment]
This is not a bug, but an intentional feature. We do not allow users to unequip items so that they suffer. And also users usually don't know what they will enjoy, so we simply guide them with some enforcement.

**Comment by cahidenes** [comment]
2. cumle cidden dogru bu arada

**Comment by hikasap** [comment]
Fixed!
